run:
  timeout: 5m
linters:
  enable:
    - asciicheck
    - depguard
    - dogsled
    - durationcheck
    - errcheck
    - errorlint
    - exportloopref
    - gci
    - gofmt
    - goimports
    - gosec
    - misspell
    - nakedret
    - nilerr
    - nolintlint
    - revive
    - wastedassign
    - bidichk
    - contextcheck
    - cyclop
    - dupl
    - goheader
linters-settings:
  goimports:
    local-prefixes: github.com/ko-han/qudis
  goheader:
    template-path: license.txt
issues:
  exclude-rules:
    - linters:
        - structcheck
        - unused
      text: "`data` is unused"
    - linters:
        - staticcheck
      text: "SA1019:"
    - linters:
        - revive
      text: "var-naming:"
    - linters:
        - revive
      text: "exported:"
    - path: _test\.go
      linters:
        - gosec # security is not make sense in tests
